server:
  port: 8080

spring:
  application:
    name: royal-stay
  
  datasource:
    url: jdbc:mysql://localhost:3306/royal_stay_db?createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:royalStaySecretKey2024ForJWTTokenGeneration}
  expiration: 86400000

# AWS S3 Configuration
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET:royal-stay-bucket}
    access-key: ${AWS_ACCESS_KEY:your-access-key}
    secret-key: ${AWS_SECRET_KEY:your-secret-key}
    region: ${AWS_REGION:us-east-1}

logging:
  level:
    com.royalstay: DEBUG
    org.springframework.security: DEBUG
